name: Release

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    container: almalinux:8

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/rustup-mirror
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
