name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: almalinux:8
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Deps setup
      run: dnf -y install gcc openssl-devel
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: rustup-mirror
        path: target/release/rustup-mirror
